steps:
  # Build the container image using buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-backend'
      - '--image=gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=core.settings,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--max-instances=10'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'

images:
  - 'gcr.io/$PROJECT_ID/portfolio-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
