# Generated by Django 5.2.7 on 2025-11-01 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("infrastructure", "Infrastructure"),
                            ("ai_ml", "AI/ML"),
                            ("database", "Database"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("color", models.CharField(default="blue", max_length=20)),
                ("proficiency_level", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Tech Stack",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tech_stack",
                    models.ManyToManyField(
                        related_name="projects", to="portfolio.techstack"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(help_text="What I learned")),
                ("challenges", models.TextField(help_text="Challenges faced")),
                ("outcomes", models.TextField(help_text="What I built")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tech_stack",
                    models.ManyToManyField(
                        related_name="journey_entries", to="portfolio.techstack"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journey Entries",
                "ordering": ["hour"],
            },
        ),
    ]
