# Generated by Django 5.2.7 on 2025-11-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("papers_found", models.IntegerField(default=0)),
                ("papers_added", models.IntegerField(default=0)),
                ("papers_updated", models.IntegerField(default=0)),
                ("errors", models.TextField(blank=True)),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Scraper Jobs",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                (
                    "authors",
                    models.TextField(help_text="Comma-separated list of authors"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("arxiv", "arXiv"),
                            ("huggingface", "Hugging Face"),
                            ("paperswithcode", "Papers with Code"),
                            ("scholar", "Google Scholar"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Unique ID from source", max_length=200, unique=True
                    ),
                ),
                ("url", models.URLField()),
                ("pdf_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("published_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("llm", "Large Language Models"),
                            ("cv", "Computer Vision"),
                            ("rag", "RAG & Embeddings"),
                            ("mlops", "MLOps & Platform"),
                            ("training", "Training & Optimization"),
                            ("inference", "Inference & Deployment"),
                            ("nlp", "Natural Language Processing"),
                            ("multimodal", "Multimodal AI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text='["transformers", "attention", ...]'
                    ),
                ),
                ("citation_count", models.IntegerField(default=0)),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0, help_text="0-1 score based on relevance"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Papers",
                "ordering": ["-published_date", "-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["-published_date"],
                        name="portfolio_p_publish_deae85_idx",
                    ),
                    models.Index(
                        fields=["category"], name="portfolio_p_categor_befa46_idx"
                    ),
                    models.Index(
                        fields=["source"], name="portfolio_p_source_ef1857_idx"
                    ),
                ],
            },
        ),
    ]
