# Generated by Django 5.2.7 on 2025-11-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_scraperjob_paper"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={
                "ordering": ["-published_date", "-relevance_score"],
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.AlterField(
            model_name="paper",
            name="abstract",
            field=models.TextField(help_text="Full blog post content"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="authors",
            field=models.TextField(default="Vasu Kapoor", help_text="Author name(s)"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="citation_count",
            field=models.IntegerField(
                default=0, help_text="Engagement metric (views/shares)"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="relevance_score",
            field=models.FloatField(
                default=0.0, help_text="0-1 quality/relevance score"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="source",
            field=models.CharField(
                choices=[
                    ("blog", "Blog Post"),
                    ("arxiv", "arXiv"),
                    ("huggingface", "Hugging Face"),
                    ("paperswithcode", "Papers with Code"),
                    ("scholar", "Google Scholar"),
                ],
                default="blog",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="source_id",
            field=models.CharField(
                help_text="Unique slug/ID", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="url",
            field=models.URLField(
                blank=True, help_text="External URL if applicable", null=True
            ),
        ),
    ]
